gdjs.Main_32MenuCode = {};
gdjs.Main_32MenuCode.GDLevel1Objects1= [];
gdjs.Main_32MenuCode.GDLevel1Objects2= [];
gdjs.Main_32MenuCode.GDLevel1Objects3= [];
gdjs.Main_32MenuCode.GDLevel2Objects1= [];
gdjs.Main_32MenuCode.GDLevel2Objects2= [];
gdjs.Main_32MenuCode.GDLevel2Objects3= [];
gdjs.Main_32MenuCode.GDLevel3Objects1= [];
gdjs.Main_32MenuCode.GDLevel3Objects2= [];
gdjs.Main_32MenuCode.GDLevel3Objects3= [];
gdjs.Main_32MenuCode.GDGamename_9595Objects1= [];
gdjs.Main_32MenuCode.GDGamename_9595Objects2= [];
gdjs.Main_32MenuCode.GDGamename_9595Objects3= [];
gdjs.Main_32MenuCode.GDBlueSpaceObjects1= [];
gdjs.Main_32MenuCode.GDBlueSpaceObjects2= [];
gdjs.Main_32MenuCode.GDBlueSpaceObjects3= [];
gdjs.Main_32MenuCode.GDBlackSpaceObjects1= [];
gdjs.Main_32MenuCode.GDBlackSpaceObjects2= [];
gdjs.Main_32MenuCode.GDBlackSpaceObjects3= [];
gdjs.Main_32MenuCode.GDBlueSpaceship2Objects1= [];
gdjs.Main_32MenuCode.GDBlueSpaceship2Objects2= [];
gdjs.Main_32MenuCode.GDBlueSpaceship2Objects3= [];
gdjs.Main_32MenuCode.GDBackgroundObjects1= [];
gdjs.Main_32MenuCode.GDBackgroundObjects2= [];
gdjs.Main_32MenuCode.GDBackgroundObjects3= [];
gdjs.Main_32MenuCode.GDPurpleSpaceObjects1= [];
gdjs.Main_32MenuCode.GDPurpleSpaceObjects2= [];
gdjs.Main_32MenuCode.GDPurpleSpaceObjects3= [];
gdjs.Main_32MenuCode.GDBlueUfoObjects1= [];
gdjs.Main_32MenuCode.GDBlueUfoObjects2= [];
gdjs.Main_32MenuCode.GDBlueUfoObjects3= [];
gdjs.Main_32MenuCode.GDBlueSpaceship1Objects1= [];
gdjs.Main_32MenuCode.GDBlueSpaceship1Objects2= [];
gdjs.Main_32MenuCode.GDBlueSpaceship1Objects3= [];
gdjs.Main_32MenuCode.GDBlueSpaceship3Objects1= [];
gdjs.Main_32MenuCode.GDBlueSpaceship3Objects2= [];
gdjs.Main_32MenuCode.GDBlueSpaceship3Objects3= [];
gdjs.Main_32MenuCode.GDGreenUfoObjects1= [];
gdjs.Main_32MenuCode.GDGreenUfoObjects2= [];
gdjs.Main_32MenuCode.GDGreenUfoObjects3= [];
gdjs.Main_32MenuCode.GDGreenSpaceship3Objects1= [];
gdjs.Main_32MenuCode.GDGreenSpaceship3Objects2= [];
gdjs.Main_32MenuCode.GDGreenSpaceship3Objects3= [];
gdjs.Main_32MenuCode.GDGreenSpaceship1Objects1= [];
gdjs.Main_32MenuCode.GDGreenSpaceship1Objects2= [];
gdjs.Main_32MenuCode.GDGreenSpaceship1Objects3= [];
gdjs.Main_32MenuCode.GDGreenSpaceship2Objects1= [];
gdjs.Main_32MenuCode.GDGreenSpaceship2Objects2= [];
gdjs.Main_32MenuCode.GDGreenSpaceship2Objects3= [];
gdjs.Main_32MenuCode.GDOrangeSpaceship1Objects1= [];
gdjs.Main_32MenuCode.GDOrangeSpaceship1Objects2= [];
gdjs.Main_32MenuCode.GDOrangeSpaceship1Objects3= [];
gdjs.Main_32MenuCode.GDRedSpaceship1Objects1= [];
gdjs.Main_32MenuCode.GDRedSpaceship1Objects2= [];
gdjs.Main_32MenuCode.GDRedSpaceship1Objects3= [];
gdjs.Main_32MenuCode.GDRedSpaceship2Objects1= [];
gdjs.Main_32MenuCode.GDRedSpaceship2Objects2= [];
gdjs.Main_32MenuCode.GDRedSpaceship2Objects3= [];
gdjs.Main_32MenuCode.GDOrangeSpaceship2Objects1= [];
gdjs.Main_32MenuCode.GDOrangeSpaceship2Objects2= [];
gdjs.Main_32MenuCode.GDOrangeSpaceship2Objects3= [];
gdjs.Main_32MenuCode.GDYellowUfoObjects1= [];
gdjs.Main_32MenuCode.GDYellowUfoObjects2= [];
gdjs.Main_32MenuCode.GDYellowUfoObjects3= [];
gdjs.Main_32MenuCode.GDOrangeSpaceship3Objects1= [];
gdjs.Main_32MenuCode.GDOrangeSpaceship3Objects2= [];
gdjs.Main_32MenuCode.GDOrangeSpaceship3Objects3= [];
gdjs.Main_32MenuCode.GDEnemy2Objects1= [];
gdjs.Main_32MenuCode.GDEnemy2Objects2= [];
gdjs.Main_32MenuCode.GDEnemy2Objects3= [];
gdjs.Main_32MenuCode.GDRedUfoObjects1= [];
gdjs.Main_32MenuCode.GDRedUfoObjects2= [];
gdjs.Main_32MenuCode.GDRedUfoObjects3= [];
gdjs.Main_32MenuCode.GDPlayerObjects1= [];
gdjs.Main_32MenuCode.GDPlayerObjects2= [];
gdjs.Main_32MenuCode.GDPlayerObjects3= [];
gdjs.Main_32MenuCode.GDBlackSpaceship3Objects1= [];
gdjs.Main_32MenuCode.GDBlackSpaceship3Objects2= [];
gdjs.Main_32MenuCode.GDBlackSpaceship3Objects3= [];
gdjs.Main_32MenuCode.GDBlackSpaceship4Objects1= [];
gdjs.Main_32MenuCode.GDBlackSpaceship4Objects2= [];
gdjs.Main_32MenuCode.GDBlackSpaceship4Objects3= [];
gdjs.Main_32MenuCode.GDBlackSpaceship5Objects1= [];
gdjs.Main_32MenuCode.GDBlackSpaceship5Objects2= [];
gdjs.Main_32MenuCode.GDBlackSpaceship5Objects3= [];
gdjs.Main_32MenuCode.GDBlueSpaceship4Objects1= [];
gdjs.Main_32MenuCode.GDBlueSpaceship4Objects2= [];
gdjs.Main_32MenuCode.GDBlueSpaceship4Objects3= [];
gdjs.Main_32MenuCode.GDBlackSpaceship2Objects1= [];
gdjs.Main_32MenuCode.GDBlackSpaceship2Objects2= [];
gdjs.Main_32MenuCode.GDBlackSpaceship2Objects3= [];
gdjs.Main_32MenuCode.GDEnemy1Objects1= [];
gdjs.Main_32MenuCode.GDEnemy1Objects2= [];
gdjs.Main_32MenuCode.GDEnemy1Objects3= [];
gdjs.Main_32MenuCode.GDBlueSpaceship6Objects1= [];
gdjs.Main_32MenuCode.GDBlueSpaceship6Objects2= [];
gdjs.Main_32MenuCode.GDBlueSpaceship6Objects3= [];
gdjs.Main_32MenuCode.GDBlueSpaceship7Objects1= [];
gdjs.Main_32MenuCode.GDBlueSpaceship7Objects2= [];
gdjs.Main_32MenuCode.GDBlueSpaceship7Objects3= [];
gdjs.Main_32MenuCode.GDBlueSpaceship8Objects1= [];
gdjs.Main_32MenuCode.GDBlueSpaceship8Objects2= [];
gdjs.Main_32MenuCode.GDBlueSpaceship8Objects3= [];
gdjs.Main_32MenuCode.GDGreenSpaceship4Objects1= [];
gdjs.Main_32MenuCode.GDGreenSpaceship4Objects2= [];
gdjs.Main_32MenuCode.GDGreenSpaceship4Objects3= [];
gdjs.Main_32MenuCode.GDGreenSpaceship5Objects1= [];
gdjs.Main_32MenuCode.GDGreenSpaceship5Objects2= [];
gdjs.Main_32MenuCode.GDGreenSpaceship5Objects3= [];
gdjs.Main_32MenuCode.GDGreenSpaceship6Objects1= [];
gdjs.Main_32MenuCode.GDGreenSpaceship6Objects2= [];
gdjs.Main_32MenuCode.GDGreenSpaceship6Objects3= [];
gdjs.Main_32MenuCode.GDGreenSpaceship7Objects1= [];
gdjs.Main_32MenuCode.GDGreenSpaceship7Objects2= [];
gdjs.Main_32MenuCode.GDGreenSpaceship7Objects3= [];
gdjs.Main_32MenuCode.GDGreenSpaceship8Objects1= [];
gdjs.Main_32MenuCode.GDGreenSpaceship8Objects2= [];
gdjs.Main_32MenuCode.GDGreenSpaceship8Objects3= [];
gdjs.Main_32MenuCode.GDRedSpaceship4Objects1= [];
gdjs.Main_32MenuCode.GDRedSpaceship4Objects2= [];
gdjs.Main_32MenuCode.GDRedSpaceship4Objects3= [];
gdjs.Main_32MenuCode.GDRedSpaceship5Objects1= [];
gdjs.Main_32MenuCode.GDRedSpaceship5Objects2= [];
gdjs.Main_32MenuCode.GDRedSpaceship5Objects3= [];
gdjs.Main_32MenuCode.GDRedSpaceship6Objects1= [];
gdjs.Main_32MenuCode.GDRedSpaceship6Objects2= [];
gdjs.Main_32MenuCode.GDRedSpaceship6Objects3= [];
gdjs.Main_32MenuCode.GDBigBrownMeteor1Objects1= [];
gdjs.Main_32MenuCode.GDBigBrownMeteor1Objects2= [];
gdjs.Main_32MenuCode.GDBigBrownMeteor1Objects3= [];
gdjs.Main_32MenuCode.GDBigBrownMeteor2Objects1= [];
gdjs.Main_32MenuCode.GDBigBrownMeteor2Objects2= [];
gdjs.Main_32MenuCode.GDBigBrownMeteor2Objects3= [];
gdjs.Main_32MenuCode.GDBigBrownMeteor3Objects1= [];
gdjs.Main_32MenuCode.GDBigBrownMeteor3Objects2= [];
gdjs.Main_32MenuCode.GDBigBrownMeteor3Objects3= [];
gdjs.Main_32MenuCode.GDMeteor1Objects1= [];
gdjs.Main_32MenuCode.GDMeteor1Objects2= [];
gdjs.Main_32MenuCode.GDMeteor1Objects3= [];
gdjs.Main_32MenuCode.GDRedSpaceship7Objects1= [];
gdjs.Main_32MenuCode.GDRedSpaceship7Objects2= [];
gdjs.Main_32MenuCode.GDRedSpaceship7Objects3= [];
gdjs.Main_32MenuCode.GDBigGreyMeteor1Objects1= [];
gdjs.Main_32MenuCode.GDBigGreyMeteor1Objects2= [];
gdjs.Main_32MenuCode.GDBigGreyMeteor1Objects3= [];
gdjs.Main_32MenuCode.GDMeteor2Objects1= [];
gdjs.Main_32MenuCode.GDMeteor2Objects2= [];
gdjs.Main_32MenuCode.GDMeteor2Objects3= [];
gdjs.Main_32MenuCode.GDEnemy3Objects1= [];
gdjs.Main_32MenuCode.GDEnemy3Objects2= [];
gdjs.Main_32MenuCode.GDEnemy3Objects3= [];
gdjs.Main_32MenuCode.GDBigGreyMeteor3Objects1= [];
gdjs.Main_32MenuCode.GDBigGreyMeteor3Objects2= [];
gdjs.Main_32MenuCode.GDBigGreyMeteor3Objects3= [];
gdjs.Main_32MenuCode.GDBigGreyMeteor4Objects1= [];
gdjs.Main_32MenuCode.GDBigGreyMeteor4Objects2= [];
gdjs.Main_32MenuCode.GDBigGreyMeteor4Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaserObjects1= [];
gdjs.Main_32MenuCode.GDBlueLaserObjects2= [];
gdjs.Main_32MenuCode.GDBlueLaserObjects3= [];
gdjs.Main_32MenuCode.GDBlueLaser02Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser02Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser02Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser04Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser04Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser04Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser06Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser06Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser06Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser03Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser03Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser03Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser01Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser01Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser01Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser09Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser09Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser09Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser08Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser08Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser08Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser13Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser13Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser13Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser14Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser14Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser14Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser10Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser10Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser10Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser07Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser07Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser07Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser11Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser11Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser11Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser12Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser12Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser12Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser15Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser15Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser15Objects3= [];
gdjs.Main_32MenuCode.GDBlueLaser16Objects1= [];
gdjs.Main_32MenuCode.GDBlueLaser16Objects2= [];
gdjs.Main_32MenuCode.GDBlueLaser16Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser01Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser01Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser01Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser04Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser04Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser04Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser05Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser05Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser05Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser06Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser06Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser06Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser07Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser07Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser07Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser02Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser02Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser02Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser03Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser03Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser03Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser08Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser08Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser08Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser09Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser09Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser09Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser10Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser10Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser10Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser11Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser11Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser11Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser12Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser12Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser12Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser13Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser13Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser13Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser14Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser14Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser14Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser15Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser15Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser15Objects3= [];
gdjs.Main_32MenuCode.GDGreenLaser16Objects1= [];
gdjs.Main_32MenuCode.GDGreenLaser16Objects2= [];
gdjs.Main_32MenuCode.GDGreenLaser16Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser01Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser01Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser01Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser02Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser02Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser02Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser03Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser03Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser03Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser04Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser04Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser04Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser05Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser05Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser05Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser07Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser07Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser07Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser08Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser08Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser08Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser11Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser11Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser11Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser12Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser12Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser12Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser13Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser13Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser13Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser09Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser09Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser09Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser10Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser10Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser10Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser15Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser15Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser15Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser16Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser16Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser16Objects3= [];
gdjs.Main_32MenuCode.GDMeteor4Objects1= [];
gdjs.Main_32MenuCode.GDMeteor4Objects2= [];
gdjs.Main_32MenuCode.GDMeteor4Objects3= [];
gdjs.Main_32MenuCode.GDMediumBrownMeteor3Objects1= [];
gdjs.Main_32MenuCode.GDMediumBrownMeteor3Objects2= [];
gdjs.Main_32MenuCode.GDMediumBrownMeteor3Objects3= [];
gdjs.Main_32MenuCode.GDRedLaser14Objects1= [];
gdjs.Main_32MenuCode.GDRedLaser14Objects2= [];
gdjs.Main_32MenuCode.GDRedLaser14Objects3= [];
gdjs.Main_32MenuCode.GDMediumGreyMeteor1Objects1= [];
gdjs.Main_32MenuCode.GDMediumGreyMeteor1Objects2= [];
gdjs.Main_32MenuCode.GDMediumGreyMeteor1Objects3= [];
gdjs.Main_32MenuCode.GDMediumGreyMeteor2Objects1= [];
gdjs.Main_32MenuCode.GDMediumGreyMeteor2Objects2= [];
gdjs.Main_32MenuCode.GDMediumGreyMeteor2Objects3= [];
gdjs.Main_32MenuCode.GDBluePowerupObjects1= [];
gdjs.Main_32MenuCode.GDBluePowerupObjects2= [];
gdjs.Main_32MenuCode.GDBluePowerupObjects3= [];
gdjs.Main_32MenuCode.GDBoltBluePowerupObjects1= [];
gdjs.Main_32MenuCode.GDBoltBluePowerupObjects2= [];
gdjs.Main_32MenuCode.GDBoltBluePowerupObjects3= [];
gdjs.Main_32MenuCode.GDBoltRedPowerupObjects1= [];
gdjs.Main_32MenuCode.GDBoltRedPowerupObjects2= [];
gdjs.Main_32MenuCode.GDBoltRedPowerupObjects3= [];
gdjs.Main_32MenuCode.GDBoltGreenPowerupObjects1= [];
gdjs.Main_32MenuCode.GDBoltGreenPowerupObjects2= [];
gdjs.Main_32MenuCode.GDBoltGreenPowerupObjects3= [];
gdjs.Main_32MenuCode.GDBoltYellowPowerupObjects1= [];
gdjs.Main_32MenuCode.GDBoltYellowPowerupObjects2= [];
gdjs.Main_32MenuCode.GDBoltYellowPowerupObjects3= [];
gdjs.Main_32MenuCode.GDGoldThingsObjects1= [];
gdjs.Main_32MenuCode.GDGoldThingsObjects2= [];
gdjs.Main_32MenuCode.GDGoldThingsObjects3= [];
gdjs.Main_32MenuCode.GDRedPowerupObjects1= [];
gdjs.Main_32MenuCode.GDRedPowerupObjects2= [];
gdjs.Main_32MenuCode.GDRedPowerupObjects3= [];
gdjs.Main_32MenuCode.GDShieldBluePowerupObjects1= [];
gdjs.Main_32MenuCode.GDShieldBluePowerupObjects2= [];
gdjs.Main_32MenuCode.GDShieldBluePowerupObjects3= [];
gdjs.Main_32MenuCode.GDShieldGreenPowerupObjects1= [];
gdjs.Main_32MenuCode.GDShieldGreenPowerupObjects2= [];
gdjs.Main_32MenuCode.GDShieldGreenPowerupObjects3= [];
gdjs.Main_32MenuCode.GDShieldRedPowerupObjects1= [];
gdjs.Main_32MenuCode.GDShieldRedPowerupObjects2= [];
gdjs.Main_32MenuCode.GDShieldRedPowerupObjects3= [];
gdjs.Main_32MenuCode.GDBronzeThingsObjects1= [];
gdjs.Main_32MenuCode.GDBronzeThingsObjects2= [];
gdjs.Main_32MenuCode.GDBronzeThingsObjects3= [];
gdjs.Main_32MenuCode.GDGreenPowerupObjects1= [];
gdjs.Main_32MenuCode.GDGreenPowerupObjects2= [];
gdjs.Main_32MenuCode.GDGreenPowerupObjects3= [];
gdjs.Main_32MenuCode.GDShieldYellowPowerupObjects1= [];
gdjs.Main_32MenuCode.GDShieldYellowPowerupObjects2= [];
gdjs.Main_32MenuCode.GDShieldYellowPowerupObjects3= [];
gdjs.Main_32MenuCode.GDSilverThingsObjects1= [];
gdjs.Main_32MenuCode.GDSilverThingsObjects2= [];
gdjs.Main_32MenuCode.GDSilverThingsObjects3= [];
gdjs.Main_32MenuCode.GDStarBluePowerupObjects1= [];
gdjs.Main_32MenuCode.GDStarBluePowerupObjects2= [];
gdjs.Main_32MenuCode.GDStarBluePowerupObjects3= [];
gdjs.Main_32MenuCode.GDStarRedPowerupObjects1= [];
gdjs.Main_32MenuCode.GDStarRedPowerupObjects2= [];
gdjs.Main_32MenuCode.GDStarRedPowerupObjects3= [];
gdjs.Main_32MenuCode.GDStarGreenPowerupObjects1= [];
gdjs.Main_32MenuCode.GDStarGreenPowerupObjects2= [];
gdjs.Main_32MenuCode.GDStarGreenPowerupObjects3= [];
gdjs.Main_32MenuCode.GDStarYellowPowerupObjects1= [];
gdjs.Main_32MenuCode.GDStarYellowPowerupObjects2= [];
gdjs.Main_32MenuCode.GDStarYellowPowerupObjects3= [];
gdjs.Main_32MenuCode.GDYellowPowerupObjects1= [];
gdjs.Main_32MenuCode.GDYellowPowerupObjects2= [];
gdjs.Main_32MenuCode.GDYellowPowerupObjects3= [];
gdjs.Main_32MenuCode.GDTinyBrownMeteor2Objects1= [];
gdjs.Main_32MenuCode.GDTinyBrownMeteor2Objects2= [];
gdjs.Main_32MenuCode.GDTinyBrownMeteor2Objects3= [];
gdjs.Main_32MenuCode.GDSmallBrownMeteor2Objects1= [];
gdjs.Main_32MenuCode.GDSmallBrownMeteor2Objects2= [];
gdjs.Main_32MenuCode.GDSmallBrownMeteor2Objects3= [];
gdjs.Main_32MenuCode.GDSmallGreyMeteor1Objects1= [];
gdjs.Main_32MenuCode.GDSmallGreyMeteor1Objects2= [];
gdjs.Main_32MenuCode.GDSmallGreyMeteor1Objects3= [];
gdjs.Main_32MenuCode.GDTinyBrownMeteor1Objects1= [];
gdjs.Main_32MenuCode.GDTinyBrownMeteor1Objects2= [];
gdjs.Main_32MenuCode.GDTinyBrownMeteor1Objects3= [];
gdjs.Main_32MenuCode.GDSmallBrownMeteor1Objects1= [];
gdjs.Main_32MenuCode.GDSmallBrownMeteor1Objects2= [];
gdjs.Main_32MenuCode.GDSmallBrownMeteor1Objects3= [];
gdjs.Main_32MenuCode.GDTinyGreyMeteor2Objects1= [];
gdjs.Main_32MenuCode.GDTinyGreyMeteor2Objects2= [];
gdjs.Main_32MenuCode.GDTinyGreyMeteor2Objects3= [];
gdjs.Main_32MenuCode.GDGoldBoltObjects1= [];
gdjs.Main_32MenuCode.GDGoldBoltObjects2= [];
gdjs.Main_32MenuCode.GDGoldBoltObjects3= [];
gdjs.Main_32MenuCode.GDTinyGreyMeteor1Objects1= [];
gdjs.Main_32MenuCode.GDTinyGreyMeteor1Objects2= [];
gdjs.Main_32MenuCode.GDTinyGreyMeteor1Objects3= [];
gdjs.Main_32MenuCode.GDBronzeBoltObjects1= [];
gdjs.Main_32MenuCode.GDBronzeBoltObjects2= [];
gdjs.Main_32MenuCode.GDBronzeBoltObjects3= [];
gdjs.Main_32MenuCode.GDBluePillObjects1= [];
gdjs.Main_32MenuCode.GDBluePillObjects2= [];
gdjs.Main_32MenuCode.GDBluePillObjects3= [];
gdjs.Main_32MenuCode.GDBronzeShieldObjects1= [];
gdjs.Main_32MenuCode.GDBronzeShieldObjects2= [];
gdjs.Main_32MenuCode.GDBronzeShieldObjects3= [];
gdjs.Main_32MenuCode.GDBronzeStarObjects1= [];
gdjs.Main_32MenuCode.GDBronzeStarObjects2= [];
gdjs.Main_32MenuCode.GDBronzeStarObjects3= [];
gdjs.Main_32MenuCode.GDGoldShieldObjects1= [];
gdjs.Main_32MenuCode.GDGoldShieldObjects2= [];
gdjs.Main_32MenuCode.GDGoldShieldObjects3= [];
gdjs.Main_32MenuCode.GDGreenPillObjects1= [];
gdjs.Main_32MenuCode.GDGreenPillObjects2= [];
gdjs.Main_32MenuCode.GDGreenPillObjects3= [];
gdjs.Main_32MenuCode.GDSilverBoltObjects1= [];
gdjs.Main_32MenuCode.GDSilverBoltObjects2= [];
gdjs.Main_32MenuCode.GDSilverBoltObjects3= [];
gdjs.Main_32MenuCode.GDSilverShieldObjects1= [];
gdjs.Main_32MenuCode.GDSilverShieldObjects2= [];
gdjs.Main_32MenuCode.GDSilverShieldObjects3= [];
gdjs.Main_32MenuCode.GDSilverStarObjects1= [];
gdjs.Main_32MenuCode.GDSilverStarObjects2= [];
gdjs.Main_32MenuCode.GDSilverStarObjects3= [];
gdjs.Main_32MenuCode.GDYellowPillObjects1= [];
gdjs.Main_32MenuCode.GDYellowPillObjects2= [];
gdjs.Main_32MenuCode.GDYellowPillObjects3= [];
gdjs.Main_32MenuCode.GDGoldStarObjects1= [];
gdjs.Main_32MenuCode.GDGoldStarObjects2= [];
gdjs.Main_32MenuCode.GDGoldStarObjects3= [];
gdjs.Main_32MenuCode.GDRedPillObjects1= [];
gdjs.Main_32MenuCode.GDRedPillObjects2= [];
gdjs.Main_32MenuCode.GDRedPillObjects3= [];


gdjs.Main_32MenuCode.mapOfGDgdjs_9546Main_959532MenuCode_9546GDLevel1Objects2Objects = Hashtable.newFrom({"Level1": gdjs.Main_32MenuCode.GDLevel1Objects2});
gdjs.Main_32MenuCode.mapOfGDgdjs_9546Main_959532MenuCode_9546GDLevel2Objects2Objects = Hashtable.newFrom({"Level2": gdjs.Main_32MenuCode.GDLevel2Objects2});
gdjs.Main_32MenuCode.mapOfGDgdjs_9546Main_959532MenuCode_9546GDLevel3Objects1Objects = Hashtable.newFrom({"Level3": gdjs.Main_32MenuCode.GDLevel3Objects1});
gdjs.Main_32MenuCode.eventsList0 = function(runtimeScene) {

{

gdjs.copyArray(gdjs.Main_32MenuCode.GDLevel1Objects1, gdjs.Main_32MenuCode.GDLevel1Objects2);


let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.input.cursorOnObject(gdjs.Main_32MenuCode.mapOfGDgdjs_9546Main_959532MenuCode_9546GDLevel1Objects2Objects, runtimeScene, true, false);
if (isConditionTrue_0) {
{runtimeScene.getGame().getVariables().getFromIndex(0).setNumber(1);
}{gdjs.evtTools.runtimeScene.replaceScene(runtimeScene, "PlayScene", false);
}}

}


{

gdjs.copyArray(gdjs.Main_32MenuCode.GDLevel2Objects1, gdjs.Main_32MenuCode.GDLevel2Objects2);


let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.input.cursorOnObject(gdjs.Main_32MenuCode.mapOfGDgdjs_9546Main_959532MenuCode_9546GDLevel2Objects2Objects, runtimeScene, true, false);
if (isConditionTrue_0) {
{runtimeScene.getGame().getVariables().getFromIndex(0).setNumber(2);
}{gdjs.evtTools.runtimeScene.replaceScene(runtimeScene, "PlayScene", false);
}}

}


{

/* Reuse gdjs.Main_32MenuCode.GDLevel3Objects1 */

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.input.cursorOnObject(gdjs.Main_32MenuCode.mapOfGDgdjs_9546Main_959532MenuCode_9546GDLevel3Objects1Objects, runtimeScene, true, false);
if (isConditionTrue_0) {
{runtimeScene.getGame().getVariables().getFromIndex(0).setNumber(3);
}{gdjs.evtTools.runtimeScene.replaceScene(runtimeScene, "PlayScene", false);
}}

}


};gdjs.Main_32MenuCode.eventsList1 = function(runtimeScene) {

{

gdjs.copyArray(runtimeScene.getObjects("Level1"), gdjs.Main_32MenuCode.GDLevel1Objects1);
gdjs.copyArray(runtimeScene.getObjects("Level2"), gdjs.Main_32MenuCode.GDLevel2Objects1);
gdjs.copyArray(runtimeScene.getObjects("Level3"), gdjs.Main_32MenuCode.GDLevel3Objects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.input.isMouseButtonPressed(runtimeScene, "Left");
if (isConditionTrue_0) {
isConditionTrue_0 = false;
for (var i = 0, k = 0, l = gdjs.Main_32MenuCode.GDLevel1Objects1.length;i<l;++i) {
    if ( gdjs.Main_32MenuCode.GDLevel1Objects1[i].getBehavior("Animation").getAnimationName() == "Unlocked" ) {
        isConditionTrue_0 = true;
        gdjs.Main_32MenuCode.GDLevel1Objects1[k] = gdjs.Main_32MenuCode.GDLevel1Objects1[i];
        ++k;
    }
}
gdjs.Main_32MenuCode.GDLevel1Objects1.length = k;
for (var i = 0, k = 0, l = gdjs.Main_32MenuCode.GDLevel2Objects1.length;i<l;++i) {
    if ( gdjs.Main_32MenuCode.GDLevel2Objects1[i].getBehavior("Animation").getAnimationName() == "Unlocked" ) {
        isConditionTrue_0 = true;
        gdjs.Main_32MenuCode.GDLevel2Objects1[k] = gdjs.Main_32MenuCode.GDLevel2Objects1[i];
        ++k;
    }
}
gdjs.Main_32MenuCode.GDLevel2Objects1.length = k;
for (var i = 0, k = 0, l = gdjs.Main_32MenuCode.GDLevel3Objects1.length;i<l;++i) {
    if ( gdjs.Main_32MenuCode.GDLevel3Objects1[i].getBehavior("Animation").getAnimationName() == "Unlocked" ) {
        isConditionTrue_0 = true;
        gdjs.Main_32MenuCode.GDLevel3Objects1[k] = gdjs.Main_32MenuCode.GDLevel3Objects1[i];
        ++k;
    }
}
gdjs.Main_32MenuCode.GDLevel3Objects1.length = k;
}
if (isConditionTrue_0) {

{ //Subevents
gdjs.Main_32MenuCode.eventsList0(runtimeScene);} //End of subevents
}

}


{


let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.variable.getVariableNumber(runtimeScene.getGame().getVariables().getFromIndex(0)) >= 2;
if (isConditionTrue_0) {
gdjs.copyArray(runtimeScene.getObjects("Level2"), gdjs.Main_32MenuCode.GDLevel2Objects1);
{for(var i = 0, len = gdjs.Main_32MenuCode.GDLevel2Objects1.length ;i < len;++i) {
    gdjs.Main_32MenuCode.GDLevel2Objects1[i].getBehavior("Animation").setAnimationName("Unlocked");
}
}}

}


{


let isConditionTrue_0 = false;
isConditionTrue_0 = false;
isConditionTrue_0 = gdjs.evtTools.variable.getVariableNumber(runtimeScene.getGame().getVariables().getFromIndex(0)) >= 3;
if (isConditionTrue_0) {
gdjs.copyArray(runtimeScene.getObjects("Level3"), gdjs.Main_32MenuCode.GDLevel3Objects1);
{for(var i = 0, len = gdjs.Main_32MenuCode.GDLevel3Objects1.length ;i < len;++i) {
    gdjs.Main_32MenuCode.GDLevel3Objects1[i].getBehavior("Animation").setAnimationName("Unlocked");
}
}}

}


};

gdjs.Main_32MenuCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();

gdjs.Main_32MenuCode.GDLevel1Objects1.length = 0;
gdjs.Main_32MenuCode.GDLevel1Objects2.length = 0;
gdjs.Main_32MenuCode.GDLevel1Objects3.length = 0;
gdjs.Main_32MenuCode.GDLevel2Objects1.length = 0;
gdjs.Main_32MenuCode.GDLevel2Objects2.length = 0;
gdjs.Main_32MenuCode.GDLevel2Objects3.length = 0;
gdjs.Main_32MenuCode.GDLevel3Objects1.length = 0;
gdjs.Main_32MenuCode.GDLevel3Objects2.length = 0;
gdjs.Main_32MenuCode.GDLevel3Objects3.length = 0;
gdjs.Main_32MenuCode.GDGamename_9595Objects1.length = 0;
gdjs.Main_32MenuCode.GDGamename_9595Objects2.length = 0;
gdjs.Main_32MenuCode.GDGamename_9595Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceObjects1.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceObjects2.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceObjects3.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceObjects1.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceObjects2.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceObjects3.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship2Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship2Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship2Objects3.length = 0;
gdjs.Main_32MenuCode.GDBackgroundObjects1.length = 0;
gdjs.Main_32MenuCode.GDBackgroundObjects2.length = 0;
gdjs.Main_32MenuCode.GDBackgroundObjects3.length = 0;
gdjs.Main_32MenuCode.GDPurpleSpaceObjects1.length = 0;
gdjs.Main_32MenuCode.GDPurpleSpaceObjects2.length = 0;
gdjs.Main_32MenuCode.GDPurpleSpaceObjects3.length = 0;
gdjs.Main_32MenuCode.GDBlueUfoObjects1.length = 0;
gdjs.Main_32MenuCode.GDBlueUfoObjects2.length = 0;
gdjs.Main_32MenuCode.GDBlueUfoObjects3.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship1Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship1Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship1Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship3Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship3Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship3Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenUfoObjects1.length = 0;
gdjs.Main_32MenuCode.GDGreenUfoObjects2.length = 0;
gdjs.Main_32MenuCode.GDGreenUfoObjects3.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship3Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship3Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship3Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship1Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship1Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship1Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship2Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship2Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship2Objects3.length = 0;
gdjs.Main_32MenuCode.GDOrangeSpaceship1Objects1.length = 0;
gdjs.Main_32MenuCode.GDOrangeSpaceship1Objects2.length = 0;
gdjs.Main_32MenuCode.GDOrangeSpaceship1Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship1Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship1Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship1Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship2Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship2Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship2Objects3.length = 0;
gdjs.Main_32MenuCode.GDOrangeSpaceship2Objects1.length = 0;
gdjs.Main_32MenuCode.GDOrangeSpaceship2Objects2.length = 0;
gdjs.Main_32MenuCode.GDOrangeSpaceship2Objects3.length = 0;
gdjs.Main_32MenuCode.GDYellowUfoObjects1.length = 0;
gdjs.Main_32MenuCode.GDYellowUfoObjects2.length = 0;
gdjs.Main_32MenuCode.GDYellowUfoObjects3.length = 0;
gdjs.Main_32MenuCode.GDOrangeSpaceship3Objects1.length = 0;
gdjs.Main_32MenuCode.GDOrangeSpaceship3Objects2.length = 0;
gdjs.Main_32MenuCode.GDOrangeSpaceship3Objects3.length = 0;
gdjs.Main_32MenuCode.GDEnemy2Objects1.length = 0;
gdjs.Main_32MenuCode.GDEnemy2Objects2.length = 0;
gdjs.Main_32MenuCode.GDEnemy2Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedUfoObjects1.length = 0;
gdjs.Main_32MenuCode.GDRedUfoObjects2.length = 0;
gdjs.Main_32MenuCode.GDRedUfoObjects3.length = 0;
gdjs.Main_32MenuCode.GDPlayerObjects1.length = 0;
gdjs.Main_32MenuCode.GDPlayerObjects2.length = 0;
gdjs.Main_32MenuCode.GDPlayerObjects3.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship3Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship3Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship3Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship4Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship4Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship4Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship5Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship5Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship5Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship4Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship4Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship4Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship2Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship2Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlackSpaceship2Objects3.length = 0;
gdjs.Main_32MenuCode.GDEnemy1Objects1.length = 0;
gdjs.Main_32MenuCode.GDEnemy1Objects2.length = 0;
gdjs.Main_32MenuCode.GDEnemy1Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship6Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship6Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship6Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship7Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship7Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship7Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship8Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship8Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueSpaceship8Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship4Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship4Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship4Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship5Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship5Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship5Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship6Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship6Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship6Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship7Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship7Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship7Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship8Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship8Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenSpaceship8Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship4Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship4Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship4Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship5Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship5Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship5Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship6Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship6Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship6Objects3.length = 0;
gdjs.Main_32MenuCode.GDBigBrownMeteor1Objects1.length = 0;
gdjs.Main_32MenuCode.GDBigBrownMeteor1Objects2.length = 0;
gdjs.Main_32MenuCode.GDBigBrownMeteor1Objects3.length = 0;
gdjs.Main_32MenuCode.GDBigBrownMeteor2Objects1.length = 0;
gdjs.Main_32MenuCode.GDBigBrownMeteor2Objects2.length = 0;
gdjs.Main_32MenuCode.GDBigBrownMeteor2Objects3.length = 0;
gdjs.Main_32MenuCode.GDBigBrownMeteor3Objects1.length = 0;
gdjs.Main_32MenuCode.GDBigBrownMeteor3Objects2.length = 0;
gdjs.Main_32MenuCode.GDBigBrownMeteor3Objects3.length = 0;
gdjs.Main_32MenuCode.GDMeteor1Objects1.length = 0;
gdjs.Main_32MenuCode.GDMeteor1Objects2.length = 0;
gdjs.Main_32MenuCode.GDMeteor1Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship7Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship7Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedSpaceship7Objects3.length = 0;
gdjs.Main_32MenuCode.GDBigGreyMeteor1Objects1.length = 0;
gdjs.Main_32MenuCode.GDBigGreyMeteor1Objects2.length = 0;
gdjs.Main_32MenuCode.GDBigGreyMeteor1Objects3.length = 0;
gdjs.Main_32MenuCode.GDMeteor2Objects1.length = 0;
gdjs.Main_32MenuCode.GDMeteor2Objects2.length = 0;
gdjs.Main_32MenuCode.GDMeteor2Objects3.length = 0;
gdjs.Main_32MenuCode.GDEnemy3Objects1.length = 0;
gdjs.Main_32MenuCode.GDEnemy3Objects2.length = 0;
gdjs.Main_32MenuCode.GDEnemy3Objects3.length = 0;
gdjs.Main_32MenuCode.GDBigGreyMeteor3Objects1.length = 0;
gdjs.Main_32MenuCode.GDBigGreyMeteor3Objects2.length = 0;
gdjs.Main_32MenuCode.GDBigGreyMeteor3Objects3.length = 0;
gdjs.Main_32MenuCode.GDBigGreyMeteor4Objects1.length = 0;
gdjs.Main_32MenuCode.GDBigGreyMeteor4Objects2.length = 0;
gdjs.Main_32MenuCode.GDBigGreyMeteor4Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaserObjects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaserObjects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaserObjects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser02Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser02Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser02Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser04Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser04Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser04Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser06Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser06Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser06Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser03Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser03Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser03Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser01Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser01Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser01Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser09Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser09Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser09Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser08Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser08Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser08Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser13Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser13Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser13Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser14Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser14Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser14Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser10Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser10Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser10Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser07Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser07Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser07Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser11Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser11Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser11Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser12Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser12Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser12Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser15Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser15Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser15Objects3.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser16Objects1.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser16Objects2.length = 0;
gdjs.Main_32MenuCode.GDBlueLaser16Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser01Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser01Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser01Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser04Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser04Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser04Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser05Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser05Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser05Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser06Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser06Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser06Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser07Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser07Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser07Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser02Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser02Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser02Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser03Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser03Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser03Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser08Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser08Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser08Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser09Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser09Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser09Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser10Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser10Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser10Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser11Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser11Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser11Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser12Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser12Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser12Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser13Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser13Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser13Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser14Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser14Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser14Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser15Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser15Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser15Objects3.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser16Objects1.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser16Objects2.length = 0;
gdjs.Main_32MenuCode.GDGreenLaser16Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser01Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser01Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser01Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser02Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser02Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser02Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser03Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser03Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser03Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser04Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser04Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser04Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser05Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser05Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser05Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser07Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser07Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser07Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser08Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser08Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser08Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser11Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser11Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser11Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser12Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser12Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser12Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser13Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser13Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser13Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser09Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser09Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser09Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser10Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser10Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser10Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser15Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser15Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser15Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser16Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser16Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser16Objects3.length = 0;
gdjs.Main_32MenuCode.GDMeteor4Objects1.length = 0;
gdjs.Main_32MenuCode.GDMeteor4Objects2.length = 0;
gdjs.Main_32MenuCode.GDMeteor4Objects3.length = 0;
gdjs.Main_32MenuCode.GDMediumBrownMeteor3Objects1.length = 0;
gdjs.Main_32MenuCode.GDMediumBrownMeteor3Objects2.length = 0;
gdjs.Main_32MenuCode.GDMediumBrownMeteor3Objects3.length = 0;
gdjs.Main_32MenuCode.GDRedLaser14Objects1.length = 0;
gdjs.Main_32MenuCode.GDRedLaser14Objects2.length = 0;
gdjs.Main_32MenuCode.GDRedLaser14Objects3.length = 0;
gdjs.Main_32MenuCode.GDMediumGreyMeteor1Objects1.length = 0;
gdjs.Main_32MenuCode.GDMediumGreyMeteor1Objects2.length = 0;
gdjs.Main_32MenuCode.GDMediumGreyMeteor1Objects3.length = 0;
gdjs.Main_32MenuCode.GDMediumGreyMeteor2Objects1.length = 0;
gdjs.Main_32MenuCode.GDMediumGreyMeteor2Objects2.length = 0;
gdjs.Main_32MenuCode.GDMediumGreyMeteor2Objects3.length = 0;
gdjs.Main_32MenuCode.GDBluePowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDBluePowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDBluePowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDBoltBluePowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDBoltBluePowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDBoltBluePowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDBoltRedPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDBoltRedPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDBoltRedPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDBoltGreenPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDBoltGreenPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDBoltGreenPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDBoltYellowPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDBoltYellowPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDBoltYellowPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDGoldThingsObjects1.length = 0;
gdjs.Main_32MenuCode.GDGoldThingsObjects2.length = 0;
gdjs.Main_32MenuCode.GDGoldThingsObjects3.length = 0;
gdjs.Main_32MenuCode.GDRedPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDRedPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDRedPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDShieldBluePowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDShieldBluePowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDShieldBluePowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDShieldGreenPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDShieldGreenPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDShieldGreenPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDShieldRedPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDShieldRedPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDShieldRedPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDBronzeThingsObjects1.length = 0;
gdjs.Main_32MenuCode.GDBronzeThingsObjects2.length = 0;
gdjs.Main_32MenuCode.GDBronzeThingsObjects3.length = 0;
gdjs.Main_32MenuCode.GDGreenPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDGreenPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDGreenPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDShieldYellowPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDShieldYellowPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDShieldYellowPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDSilverThingsObjects1.length = 0;
gdjs.Main_32MenuCode.GDSilverThingsObjects2.length = 0;
gdjs.Main_32MenuCode.GDSilverThingsObjects3.length = 0;
gdjs.Main_32MenuCode.GDStarBluePowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDStarBluePowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDStarBluePowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDStarRedPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDStarRedPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDStarRedPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDStarGreenPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDStarGreenPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDStarGreenPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDStarYellowPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDStarYellowPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDStarYellowPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDYellowPowerupObjects1.length = 0;
gdjs.Main_32MenuCode.GDYellowPowerupObjects2.length = 0;
gdjs.Main_32MenuCode.GDYellowPowerupObjects3.length = 0;
gdjs.Main_32MenuCode.GDTinyBrownMeteor2Objects1.length = 0;
gdjs.Main_32MenuCode.GDTinyBrownMeteor2Objects2.length = 0;
gdjs.Main_32MenuCode.GDTinyBrownMeteor2Objects3.length = 0;
gdjs.Main_32MenuCode.GDSmallBrownMeteor2Objects1.length = 0;
gdjs.Main_32MenuCode.GDSmallBrownMeteor2Objects2.length = 0;
gdjs.Main_32MenuCode.GDSmallBrownMeteor2Objects3.length = 0;
gdjs.Main_32MenuCode.GDSmallGreyMeteor1Objects1.length = 0;
gdjs.Main_32MenuCode.GDSmallGreyMeteor1Objects2.length = 0;
gdjs.Main_32MenuCode.GDSmallGreyMeteor1Objects3.length = 0;
gdjs.Main_32MenuCode.GDTinyBrownMeteor1Objects1.length = 0;
gdjs.Main_32MenuCode.GDTinyBrownMeteor1Objects2.length = 0;
gdjs.Main_32MenuCode.GDTinyBrownMeteor1Objects3.length = 0;
gdjs.Main_32MenuCode.GDSmallBrownMeteor1Objects1.length = 0;
gdjs.Main_32MenuCode.GDSmallBrownMeteor1Objects2.length = 0;
gdjs.Main_32MenuCode.GDSmallBrownMeteor1Objects3.length = 0;
gdjs.Main_32MenuCode.GDTinyGreyMeteor2Objects1.length = 0;
gdjs.Main_32MenuCode.GDTinyGreyMeteor2Objects2.length = 0;
gdjs.Main_32MenuCode.GDTinyGreyMeteor2Objects3.length = 0;
gdjs.Main_32MenuCode.GDGoldBoltObjects1.length = 0;
gdjs.Main_32MenuCode.GDGoldBoltObjects2.length = 0;
gdjs.Main_32MenuCode.GDGoldBoltObjects3.length = 0;
gdjs.Main_32MenuCode.GDTinyGreyMeteor1Objects1.length = 0;
gdjs.Main_32MenuCode.GDTinyGreyMeteor1Objects2.length = 0;
gdjs.Main_32MenuCode.GDTinyGreyMeteor1Objects3.length = 0;
gdjs.Main_32MenuCode.GDBronzeBoltObjects1.length = 0;
gdjs.Main_32MenuCode.GDBronzeBoltObjects2.length = 0;
gdjs.Main_32MenuCode.GDBronzeBoltObjects3.length = 0;
gdjs.Main_32MenuCode.GDBluePillObjects1.length = 0;
gdjs.Main_32MenuCode.GDBluePillObjects2.length = 0;
gdjs.Main_32MenuCode.GDBluePillObjects3.length = 0;
gdjs.Main_32MenuCode.GDBronzeShieldObjects1.length = 0;
gdjs.Main_32MenuCode.GDBronzeShieldObjects2.length = 0;
gdjs.Main_32MenuCode.GDBronzeShieldObjects3.length = 0;
gdjs.Main_32MenuCode.GDBronzeStarObjects1.length = 0;
gdjs.Main_32MenuCode.GDBronzeStarObjects2.length = 0;
gdjs.Main_32MenuCode.GDBronzeStarObjects3.length = 0;
gdjs.Main_32MenuCode.GDGoldShieldObjects1.length = 0;
gdjs.Main_32MenuCode.GDGoldShieldObjects2.length = 0;
gdjs.Main_32MenuCode.GDGoldShieldObjects3.length = 0;
gdjs.Main_32MenuCode.GDGreenPillObjects1.length = 0;
gdjs.Main_32MenuCode.GDGreenPillObjects2.length = 0;
gdjs.Main_32MenuCode.GDGreenPillObjects3.length = 0;
gdjs.Main_32MenuCode.GDSilverBoltObjects1.length = 0;
gdjs.Main_32MenuCode.GDSilverBoltObjects2.length = 0;
gdjs.Main_32MenuCode.GDSilverBoltObjects3.length = 0;
gdjs.Main_32MenuCode.GDSilverShieldObjects1.length = 0;
gdjs.Main_32MenuCode.GDSilverShieldObjects2.length = 0;
gdjs.Main_32MenuCode.GDSilverShieldObjects3.length = 0;
gdjs.Main_32MenuCode.GDSilverStarObjects1.length = 0;
gdjs.Main_32MenuCode.GDSilverStarObjects2.length = 0;
gdjs.Main_32MenuCode.GDSilverStarObjects3.length = 0;
gdjs.Main_32MenuCode.GDYellowPillObjects1.length = 0;
gdjs.Main_32MenuCode.GDYellowPillObjects2.length = 0;
gdjs.Main_32MenuCode.GDYellowPillObjects3.length = 0;
gdjs.Main_32MenuCode.GDGoldStarObjects1.length = 0;
gdjs.Main_32MenuCode.GDGoldStarObjects2.length = 0;
gdjs.Main_32MenuCode.GDGoldStarObjects3.length = 0;
gdjs.Main_32MenuCode.GDRedPillObjects1.length = 0;
gdjs.Main_32MenuCode.GDRedPillObjects2.length = 0;
gdjs.Main_32MenuCode.GDRedPillObjects3.length = 0;

gdjs.Main_32MenuCode.eventsList1(runtimeScene);

return;

}

gdjs['Main_32MenuCode'] = gdjs.Main_32MenuCode;
